print()
num1 = int(input("Digite um número: "))
num2 = int(input("Digite outro número: "))
print()
print(f"Soma: {num1 + num2}")
print()
print(f"Sub: {num1 - num2}")
print()
print(f"Mul: {num1 * num2}")
print()
print(f"Div: {num1 / num2}")
print()
print(f"Expo: {num1 ** num2}")
print()
print(f"Resto da divisão de {num1} com {num2}: {num1 % num2}")
print()
